// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-aB0YU4jZWJKZzXexWsxSQP4LqhNghnA',
    appId: '1:114237379757:web:777ee215b63aed636a6224',
    messagingSenderId: '114237379757',
    projectId: 'autopay-fba9c',
    authDomain: 'autopay-fba9c.firebaseapp.com',
    storageBucket: 'autopay-fba9c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZxFyk4bMcpbqIUszOSoHRq-oWlwEZms4',
    appId: '1:114237379757:android:ab18bfdd097a73cd6a6224',
    messagingSenderId: '114237379757',
    projectId: 'autopay-fba9c',
    storageBucket: 'autopay-fba9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXSDBnm8U58KVm4UNyaEJGjGmtN_ic_vM',
    appId: '1:114237379757:ios:ce95646eebda4f4b6a6224',
    messagingSenderId: '114237379757',
    projectId: 'autopay-fba9c',
    storageBucket: 'autopay-fba9c.appspot.com',
    iosBundleId: 'com.AutoPay.autopago',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXSDBnm8U58KVm4UNyaEJGjGmtN_ic_vM',
    appId: '1:114237379757:ios:7eff033885647db46a6224',
    messagingSenderId: '114237379757',
    projectId: 'autopay-fba9c',
    storageBucket: 'autopay-fba9c.appspot.com',
    iosBundleId: 'com.AutoPay.autopago.RunnerTests',
  );
}
